version: '3.3'
volumes:
  cosmos:
    external: true
  adguard-config:
    external: true
services:
  cosmos-cert-extractor:
    container_name: cosmos-cert-extractor
    restart: always
    volumes:
      - cosmos:/input
      - adguard-config:/output/cert
    image: 'waschinski/cosmos-cert-extractor:latest'
    environment:
      - PYTHONUNBUFFERED=0
