services:
  cert_checker:
    image: your_image_name
    environment:
      - CHECK_INTERVAL=1800  # Override the check interval to 1800 seconds (30 minutes) Default is 1 hour
    volumes:
      - cosmos:/input
      - adguard:/output
