version: '3.3'
services:
  cert_checker:
    image: ghcr.io/lilkidsuave/cosmos-cert-extractor:latest
    environment:
      - CHECK_INTERVAL=1800  # Override the check interval to 1800 seconds (30 minutes) Default is 0. Use 0 to disable timer
    volumes:
      - #CosmosDirectory:/input
      - #AdguardDirectory:/output/certs
