name: Docker Build and Push to GHCR

on:
  workflow_dispatch:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/lilkidsuave/cosmos-cert-extractor:latest
            ghcr.io/lilkidsuave/cosmos-cert-extractor:V1.0.0
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
